// examples/react-basic-demo/assets/react/App.jsx
import React, { useState } from 'react';

const App = () => {
    const [message, setMessage] = useState("Hello from React!");

    const updateDash = () => {
        setMessage("Hello from React!");
        window.dash_clientside.set_props('dash-title', { children: 'Hello from React!' });
    };

    const updateMessage = () => {
        setMessage("Hello from Dash!");
    };

    return (
        <div id="react-app" style={{ margin: "20px" }}>
            <h1 style={{ color: "#42b883" }}>{message}</h1>
            <div>
                <button id="control-dash-button" onClick={updateDash}>Control Dash</button>
            </div>
            <div hidden>
                <button id="control-react-button" onClick={updateMessage}>Control Vue</button>
            </div>
        </div>
    );
};

export default App;

// examples/vue-basic-demo/assets/vue/App.vue
<template>
  <div id="vue-app">
    <h1>{{ message }}</h1>
    <div>
      <button id="control-dash-button" @click="updateDash">Control Dash</button>
    </div>
    <div hidden>
      <button id="control-vue-button" @click="updateMessage">
        Control Vue
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";

const message = ref("Hello from Vue!");

const updateDash = () => {
  message.value = "Hello from Vue!";
  window.dash_clientside.set_props("dash-title", {
    children: "Hello from Vue!",
  });
};

const updateMessage = () => {
  message.value = "Hello from Dash!";
};
</script>

<style scoped>
#vue-app {
  margin: 20px;
}
h1 {
  color: #42b883;
}
</style>
